#!/usr/bin/env bash
# One-command setup for macOS (and Linux). Safe to re-run.
#
#   ./setup.sh
#
# Picks an Ollama model that fits the machine, installs everything, and writes a
# run.sh with the right model baked in.

set -euo pipefail
cd "$(dirname "$0")"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
have() { command -v "$1" >/dev/null 2>&1; }

# --- prerequisites -----------------------------------------------------------
say "Checking prerequisites"

# Two of the four this used to demand were never needed at runtime.
#
#   ffmpeg  PyAV ships its own — 48 binaries, libav 18, inside the wheel. The
#           only thing that wants a system ffmpeg is conform_footage.py, which
#           prepares footage on a workstation and never runs on a cabinet.
#   node    builds the interface. `frontend/dist` is what actually gets served,
#           so a machine that runs Luxora needs no JavaScript toolchain at all.
#
# Demanding all four meant an install refused on a machine that could have run
# it perfectly, and installed two things it would never execute.
missing=()
for cmd in python3; do
  have "$cmd" || missing+=("$cmd")
done

# Needed only to build the interface from source. A packaged install ships it
# already built, so this is a developer's requirement, not a customer's.
[ -d frontend/dist ] || have node || missing+=("node")

if [ ${#missing[@]} -gt 0 ]; then
  echo "  missing: ${missing[*]}"
  if have brew; then
    echo "  installing with Homebrew..."
    brew install "${missing[@]}"
  else
    echo "  install them first. On macOS:  brew install ${missing[*]}"
    exit 1
  fi
fi
echo "  all present"

# ffmpeg is optional and only for preparing footage. Say so once rather than
# failing an install over it.
have ffmpeg || echo "  (no ffmpeg — conform_footage.py needs it, nothing else does)"

# --- pick a model that fits --------------------------------------------------
# A 3B model exists in this project only because the first machine had 4 GB of
# VRAM. It conflates catalog facts — it once gave one laptop another's battery
# life. Anything with real memory should not be running it.
if [ -n "${OLLAMA_MODEL:-}" ]; then
  MODEL="$OLLAMA_MODEL"
elif [ "$(uname)" = "Darwin" ]; then
  GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
  if   [ "$GB" -ge 32 ]; then MODEL="qwen2.5:14b"
  elif [ "$GB" -ge 16 ]; then MODEL="llama3.1:8b"
  else                        MODEL="llama3.2:3b"
  fi
  echo "  ${GB} GB unified memory"
else
  MODEL="llama3.2:3b"
fi

# The MLX equivalent, for the Apple Silicon path below. Apache 2.0, so shipping
# it inside a bundle is fine.
MLX_MODEL="${MLX_MODEL:-mlx-community/Qwen2.5-7B-Instruct-4bit}"

say "Model: $MODEL"

# --- python ------------------------------------------------------------------
say "Python environment"
[ -d .venv ] || python3 -m venv .venv
./.venv/bin/python -m pip install --quiet --upgrade pip
./.venv/bin/python -m pip install --quiet -r requirements.txt
echo "  done"

# --- node --------------------------------------------------------------------
# Only when the interface has not already been built. A packaged install ships
# `frontend/dist` and never needs a JavaScript toolchain.
if [ ! -d frontend/dist ]; then
  say "Frontend"
  # Never copy node_modules or .venv between machines — both contain compiled,
  # platform-specific binaries. Install fresh on each.
  (cd frontend && npm install --silent && npm run build)
  echo "  done"
fi

# --- the local model ---------------------------------------------------------
# The fallback, not the default. Hosted answers first when GROQ_API_KEY is set,
# so every cabinet sounds alike; this is what keeps one talking when the network
# does not.
#
# MLX on Apple Silicon, by pip, into the virtualenv we just made. Ollama
# installs a system service and asks for an administrator, which is a poor thing
# to require of somebody installing a shop fitting — and MLX is Apple's own
# framework, so it is faster here besides.
if [ "$(uname -m)" = "arm64" ] && [ "$(uname)" = "Darwin" ]; then
  say "Local model (MLX, no administrator needed)"
  ./.venv/bin/python -m pip install --quiet mlx-lm
  ./.venv/bin/python -c "
from huggingface_hub import snapshot_download
snapshot_download('$MLX_MODEL')
print('  $MLX_MODEL ready')
"
elif have ollama; then
  say "Local model (Ollama, already installed here)"
  ollama serve >/dev/null 2>&1 &
  sleep 2
  ollama pull "$MODEL"
else
  say "No local model"
  echo "  Hosted answers will work. Without one, a network outage means silence."
  echo "  Install Ollama, or run this on Apple Silicon for the MLX path."
fi

say "Warming the speech model"
./.venv/bin/python -c "from backend import stt; stt._get_model(); print('  whisper ready')"

# --- run script --------------------------------------------------------------
cat > run.sh <<EOF
#!/usr/bin/env bash
# Generated by setup.sh
#
#   ./run.sh          development — API on :8000, Vite on :5173, hot reload
#   ./run.sh kiosk    what a cabinet runs: one process, built UI, models local
#   ./run.sh cloud    the platform role, for testing it before deploying
set -euo pipefail
cd "\$(dirname "\$0")"
export OLLAMA_MODEL="$MODEL"

case "\${1:-dev}" in
  kiosk)
    export LUXORA_ROLE=edge
    # Build only if there is nothing to serve and a toolchain to build with.
    # Rebuilding unconditionally put node back on a cabinet's requirements, and
    # a packaged install ships the interface already built.
    if [ ! -d frontend/dist ] && command -v npm >/dev/null 2>&1; then
      (cd frontend && npm run build)
    fi
    exec ./.venv/bin/python -m uvicorn backend.main:app --port 8000
    ;;
  cloud)
    export LUXORA_ROLE=cloud
    exec ./.venv/bin/python -m uvicorn backend.main:app --port 8000
    ;;
esac

./.venv/bin/python -m uvicorn backend.main:app --reload --port 8000 &
API=\$!
trap 'kill \$API 2>/dev/null' EXIT
cd frontend && npm run dev
EOF
chmod +x run.sh

say "Ready"
cat <<EOF

  ./run.sh          development, http://localhost:5173
  ./run.sh kiosk    single process,  http://localhost:8000

Because this machine drives the panel itself, the app runs on localhost — so the
microphone works with no HTTPS, no Chrome flags and no firewall rules.

EOF
