#!/usr/bin/env bash
# One-command setup for macOS (and Linux). Safe to re-run.
#
#   ./setup.sh
#
# Picks an Ollama model that fits the machine, installs everything, and writes a
# run.sh with the right model baked in.

set -euo pipefail
cd "$(dirname "$0")"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
have() { command -v "$1" >/dev/null 2>&1; }

# --- prerequisites -----------------------------------------------------------
say "Checking prerequisites"

missing=()
for cmd in python3 node ffmpeg ollama; do
  have "$cmd" || missing+=("$cmd")
done

if [ ${#missing[@]} -gt 0 ]; then
  echo "  missing: ${missing[*]}"
  if have brew; then
    echo "  installing with Homebrew..."
    brew install "${missing[@]}"
  else
    echo "  install them first. On macOS:"
    echo "    brew install python node ffmpeg ollama"
    exit 1
  fi
fi
echo "  all present"

# --- pick a model that fits --------------------------------------------------
# A 3B model exists in this project only because the first machine had 4 GB of
# VRAM. It conflates catalog facts — it once gave one laptop another's battery
# life. Anything with real memory should not be running it.
if [ -n "${OLLAMA_MODEL:-}" ]; then
  MODEL="$OLLAMA_MODEL"
elif [ "$(uname)" = "Darwin" ]; then
  GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
  if   [ "$GB" -ge 32 ]; then MODEL="qwen2.5:14b"
  elif [ "$GB" -ge 16 ]; then MODEL="llama3.1:8b"
  else                        MODEL="llama3.2:3b"
  fi
  echo "  ${GB} GB unified memory"
else
  MODEL="llama3.2:3b"
fi

say "Model: $MODEL"

# --- python ------------------------------------------------------------------
say "Python environment"
[ -d .venv ] || python3 -m venv .venv
./.venv/bin/python -m pip install --quiet --upgrade pip
./.venv/bin/python -m pip install --quiet -r requirements.txt
echo "  done"

# --- node --------------------------------------------------------------------
say "Frontend"
# Never copy node_modules or .venv between machines — both contain compiled,
# platform-specific binaries. Install fresh on each.
(cd frontend && npm install --silent)
echo "  done"

# --- models ------------------------------------------------------------------
say "Pulling $MODEL (this is the slow part)"
ollama serve >/dev/null 2>&1 &
sleep 2
ollama pull "$MODEL"

say "Warming the speech model"
./.venv/bin/python -c "from backend import stt; stt._get_model(); print('  whisper ready')"

# --- run script --------------------------------------------------------------
cat > run.sh <<EOF
#!/usr/bin/env bash
# Generated by setup.sh
#
#   ./run.sh          development — API on :8000, Vite on :5173, hot reload
#   ./run.sh kiosk    what a cabinet runs: one process, built UI, models local
#   ./run.sh cloud    the platform role, for testing it before deploying
set -euo pipefail
cd "\$(dirname "\$0")"
export OLLAMA_MODEL="$MODEL"

case "\${1:-dev}" in
  kiosk)
    export LUXORA_ROLE=edge
    (cd frontend && npm run build)
    exec ./.venv/bin/python -m uvicorn backend.main:app --port 8000
    ;;
  cloud)
    export LUXORA_ROLE=cloud
    exec ./.venv/bin/python -m uvicorn backend.main:app --port 8000
    ;;
esac

./.venv/bin/python -m uvicorn backend.main:app --reload --port 8000 &
API=\$!
trap 'kill \$API 2>/dev/null' EXIT
cd frontend && npm run dev
EOF
chmod +x run.sh

say "Ready"
cat <<EOF

  ./run.sh          development, http://localhost:5173
  ./run.sh kiosk    single process,  http://localhost:8000

Because this machine drives the panel itself, the app runs on localhost — so the
microphone works with no HTTPS, no Chrome flags and no firewall rules.

EOF
